SIDE-2160: Whisper Return Object in all Component Callbacks
open-olive/loop-development-kit pull request #153
Opened 2021-05-05 19:59 UTC by scottkipferOlive

Passing the whisper object back with all component callbacks will allow loop authors to utilize the `close` and eventually the `update` methods inside of the components callbacks.

Note: This PR also removes the `all` method from the whisper service.  The `all` method was left over from the thinking that whispers would have to be persisted through a loop shut down. 

- Also add an error parameter to the close method on the whisper object

2021-05-05 20:41 UTC, richseviora requested changes
I've merged in some changes to the documentation, including updating the Whisper aptitude pages (in `/docs/src/markdown-pages/aptitudes/` IIRC). That includes adding the `whisper.all` capability. Could you please drop that file in this PR as well.

2021-05-05 20:41 UTC, richseviora commented on ldk/javascript/src/types/oliveHelps/index.d.ts
> +    onClick: (whisper: Whisper) => void;
Starting to think that we should introduce a new type for these Whisper onEvent handlers... not for immediate action right now, just thinking out loud.

2021-05-05 20:48 UTC, richseviora approved these changes
Apparently I was having a senior moment; I thought I created the file but I didn't! All good then.

2021-05-06 14:46 UTC, cshields-oliveai approved these changes

2021-05-06 21:20 UTC, merged