SIDE-2107 Disclaimer and license file updates
open-olive/loop-development-kit pull request #162
Opened 2021-05-06 23:23 UTC by BrettMugglinOlive

2021-05-10 14:35 UTC, cshields-oliveai approved these changes

2021-05-17 22:22 UTC, EddieAtOlive requested changes
License content looks good, but I think we need to adjust the link(s) shown on the dev hub page.

2021-05-17 22:22 UTC, EddieAtOlive commented on docs/src/pages/index.tsx
> +            Terms & Conditions
This isn't a terms and conditions, it's a license.

I think we should have 2 links here. Something like this. I didn't include them here, but you can keep the target and rel attributes.
```html
<p>
  <a href="https://github.com/open-olive/loop-development-kit/blob/main/LICENSE">Loop Development Kit Open Source License</a>
    |
  <a href="https://olive.page.link/olive-helps-terms">Olive Helps Terms &amp; Conditions</a>
</p>
```

2021-05-17 22:22 UTC, EddieAtOlive commented on LICENSE
> +Copyright 2021 Olive AI, Inc.
The new license content looks good.

2021-05-18 13:34 UTC, EddieAtOlive commented on docs/src/pages/index.tsx
> +            Terms & Conditions
Looks good now. Thanks!

2021-05-18 13:36 UTC, EddieAtOlive approved these changes
License is correct and foot links look good now.

2021-05-18 16:22 UTC, merged