SIDE-1915: Add documentation pages for User Aptitude
open-olive/loop-development-kit pull request #182
Opened 2021-05-14 18:10 UTC by epiccoleman

2021-05-18 16:30 UTC, richseviora requested changes
Minor change

2021-05-18 16:30 UTC, richseviora commented on docs/src/markdown-pages/aptitudes/user.createJWT.md
> +Receive a JWT with the currently logged in Olive Helps user's email address in the Subject claim.
```suggestion
Receive a JWT with the currently logged in Olive Helps user's email address in the Subject (`sub`) claim.
```

2021-05-18 16:30 UTC, richseviora commented on docs/src/markdown-pages/aptitudes/user.createJWT.md
> +Receive a JWT with the currently logged in Olive Helps user's email address in the Subject claim.
I know the spec talked about other claims but I'm not sure whether they were all implemented - do we want to talk about what values are in each of them besides `exp`?

2021-06-04 15:19 UTC, epiccoleman commented
Closing this - this documentation was added in [PR 194](https://github.com/open-olive/loop-development-kit/pull/194)

2021-06-04 15:19 UTC, closed without merging