Side 1195 consolidate loop
open-olive/loop-development-kit pull request #199
Opened 2021-05-27 19:15 UTC by MaggieMaSS

This is the link of the task: https://crosschx.atlassian.net/browse/SIDE-1195

2021-05-28 17:52 UTC, MaggieMaSS commented on ldk/javascript/examples/consolidate-loop/Patient.js
> +        this._firstName = firstName;
will discard "_"

2021-05-28 17:52 UTC, MaggieMaSS commented on ldk/javascript/examples/consolidate-loop/Patient.js
> +        '_firstName',
will discard "_"?

2021-05-28 17:56 UTC, cshields-oliveai commented on ldk/javascript/examples/consolidate-loop/Patient.js
> +class Patient {
I would research a prettier for js. I see some places you have included semicolons and some you have not.

2021-05-28 17:56 UTC, MaggieMaSS commented on ldk/javascript/examples/consolidate-loop/Patient.js
> +  //TODO:
will delete todo

2021-05-28 17:59 UTC, MaggieMaSS commented on ldk/javascript/examples/consolidate-loop/Patient.js
> +    const genderList = ["Male", "Female"]
+"any"

2021-05-28 18:02 UTC, cshields-oliveai commented on ldk/javascript/examples/consolidate-loop/Patient.js
> +  setTelephone(val) {
Check if these properties are required, if they are, add some more validation to them like you had with above examples.

2021-05-28 18:04 UTC, cshields-oliveai commented on ldk/javascript/examples/consolidate-loop/README.md
> +# Building and running Loop in Olive Helps
Should we update this readme to include wording about what the consolidate example loop is, how to run it, and what kind of examples it provides?

2021-05-28 18:05 UTC, MaggieMaSS commented on ldk/javascript/examples/consolidate-loop/listenHotkey.js
> +      const hotkeys = {
indentention

2021-05-28 18:07 UTC, MaggieMaSS commented on ldk/javascript/examples/consolidate-loop/listenHotkey.js
> +                        console.log(value, patient._firstName);
delete log

2021-05-28 18:09 UTC, MaggieMaSS commented on ldk/javascript/examples/consolidate-loop/listenHotkey.js
> +                        {
time to change to js stayle

2021-05-28 18:13 UTC, MaggieMaSS commented on ldk/javascript/examples/consolidate-loop/listenHotkey.js
> +                    // Close&clear the loop after clicking submit
do we need to leave the comment?

2021-05-28 18:14 UTC, MaggieMaSS commented on ldk/javascript/examples/consolidate-loop/listenHotkey.js
> +                      let cred1 = `${patient._firstName}:${patient._lastName}:${patient._dob}`
extract the verification  as a new function

2021-05-28 18:16 UTC, cshields-oliveai commented on ldk/javascript/examples/consolidate-loop/listenHotkey.js
> +                          setTimeout(() => {
I don't believe you need `setTimeout()`

2021-05-28 18:18 UTC, MaggieMaSS commented on ldk/javascript/examples/consolidate-loop/listenHotkey.js
> +                                console.log("filesystem.writeFile callback")
Successfully saved patient record

2021-05-28 18:19 UTC, cshields-oliveai commented on ldk/javascript/examples/consolidate-loop/listenHotkey.js
> +                      instance.close && instance.close()
I believe you want `instance.close()`

2021-05-28 18:23 UTC, cshields-oliveai commented on ldk/javascript/examples/consolidate-loop/package.json
> +    "file-system": "^2.2.2"
I don't think `file-system` ref is needed.

2021-05-28 18:23 UTC, MaggieMaSS commented on ldk/javascript/tests/default-with-config/.babelrc
> +
delete the new row

2021-05-28 18:24 UTC, cshields-oliveai commented on ldk/javascript/examples/consolidate-loop/UISearch.js
> +function SearchResultWhisper(rows){
`searchResultWhisper`

2021-05-28 18:26 UTC, MaggieMaSS commented on ldk/javascript/examples/consolidate-loop/UISearch.js
> +${rst}
check the format

2021-05-28 19:21 UTC, epiccoleman commented on ldk/javascript/examples/consolidate-loop/Patient.js
> +    seralize() {
minor typo here, should be "serialize"

2021-05-28 20:16 UTC, RusGraf commented on ldk/javascript/examples/consolidate-loop/README.md
> +From `examples/typescript-loop`
probably need to update the path

2021-05-28 20:18 UTC, RusGraf commented on ldk/javascript/examples/consolidate-loop/UISearch.js
> +            text: row._firstName + ' ' + row._lastName + ' ' + row._email,// clickable, email is the distinguisher if fn&ln are same
could use string interpolation here

2021-05-28 20:20 UTC, RusGraf commented on ldk/javascript/examples/consolidate-loop/listenHotkey.js
> +                        filesystem.readFile("./PatientInfo.txt").then((data) => {
I would use await pattern here to reduce a mix of the .then/await to make it more readable.

2021-05-28 20:23 UTC, RusGraf commented on ldk/javascript/examples/consolidate-loop/package.json
> +            "value": "./PatientInfo.txt"
I believe we dont need to specify glob permissions for the  ./ any more. As long as you have "filesystem": {} you should be good to create './PatientInfo.txt'. This change was made earlier this week.

2021-06-02 00:39 UTC, richseviora requested changes, later dismissed

2021-06-08 12:02 UTC, RusGraf approved these changes

2021-06-08 23:35 UTC, BrettMugglinOlive reviewed
The name of the loop probably shouldn't be "Consolidate Loop". Maybe we should consider renaming it in file names, documentation, folder names, and variables to something like "Scheduling Example" or something like that.

What do you think?

EDIT: After bringing it up with Robin, let's rename it to "Universal Example Loop"

2021-06-08 23:37 UTC, BrettMugglinOlive commented on ldk/javascript/examples/consolidate-loop/Patient.js
> +    const cred1 = `${this.firstName}:${this.lastName}:${this.dob}`;
If email is required, do we need to check if `cred1` is true in this function?

2021-06-08 23:38 UTC, BrettMugglinOlive commented on ldk/javascript/examples/consolidate-loop/Patient.js
> +      console.error(new Error('date of birth must be as follow format: MM/DD/YYYY'));
In general, for any logs we want to use sentence case, unless the first character of the sentence is referring to a variable name. like `firstName`

2021-06-09 19:40 UTC, BrettMugglinOlive commented on ldk/javascript/examples/consolidate-loop/README.md
> +Consolidate loop demonstrates the capabilities of Olive Helps used in conjunction with each other.
"The Universal Example Loop"

2021-06-09 19:42 UTC, BrettMugglinOlive commented on ldk/javascript/examples/consolidate-loop/README.md
> +### When to use consolidate loop?
Maybe something more like "What does it do?"

2021-06-09 19:42 UTC, BrettMugglinOlive commented on ldk/javascript/examples/consolidate-loop/README.md
> +New patient appointment scheduling as a 2-step process: 1) Patient calls, scheduling staff schedules appointment. 2) Registration staff uses this information to contact patients before their appointm
"It's a patient appointment scheduling loop that is a 2-step process:..."

2021-06-09 19:45 UTC, BrettMugglinOlive commented on ldk/javascript/examples/consolidate-loop/README.md
> +3. Use firstname, lastname, date of birth, phone number or appointment date to search for patients using search bar, choose the right one if multiple records are returned.
Should either be the field names (like "firstName", "phoneNumber", etc.) or the label for the field displayed in the UI ("First Name", "Telephone", etc.)

2021-06-09 19:45 UTC, BrettMugglinOlive commented on ldk/javascript/examples/consolidate-loop/README.md
> +## Build a Loop
Build the Loop

2021-06-09 19:46 UTC, BrettMugglinOlive commented on ldk/javascript/examples/consolidate-loop/README.md
> +To build a Loop, create a new project modeled after this example.
To build the Loop

2021-06-09 19:47 UTC, BrettMugglinOlive commented on ldk/javascript/examples/consolidate-loop/README.md
> +Note that your Loop project will require a `package.json`. See "Producing Loop Compilations" in the main LDK readme for more information.
README

2021-06-09 19:49 UTC, BrettMugglinOlive commented on ldk/javascript/examples/consolidate-loop/README.md
> +All of your Loop code will begin with an `index.js` file. In this file, you define all of your Loop business logic, leveraging the LDK Aptitudes.
Can probably remove this sentence

2021-06-09 19:50 UTC, BrettMugglinOlive commented on ldk/javascript/examples/consolidate-loop/README.md
> +## Transpile the Loop for Olive Helps
Transpiling

2021-06-09 19:51 UTC, BrettMugglinOlive commented on ldk/javascript/examples/consolidate-loop/README.md
> +This will generate a `./dist` directory from your `index.js` that containes your transpiled Loop.
conatains

2021-06-09 19:52 UTC, BrettMugglinOlive commented on ldk/javascript/examples/consolidate-loop/searchBarListener.js
> +              body: `No results are found matching provided criteria`,
No results were found

2021-06-10 17:26 UTC, BrettMugglinOlive approved these changes

2021-06-10 19:20 UTC, merged