SIDE-2269 Updated Check For Polyfills
open-olive/loop-development-kit pull request #242
Opened 2021-06-22 15:58 UTC by MaggieMaSS

Updated documentation, indicating that adding Polyfills should be avoided or it could cause problems.

This is the link of the task: https://crosschx.atlassian.net/browse/SIDE-2269

2021-06-23 23:34 UTC, BrettMugglinOlive requested changes

2021-06-24 18:10 UTC, cshields-oliveai commented on docs/src/markdown-pages/guides/troubleshooting.md
> +We've already included polyfills in the LDK directly and adding other polyfills should be avoided. If you add other polyfills, the conflicting polyfills may cause problems, and we should check for po
Would it be worthwhile to direct Loop Authors where to check which polyfills have been added?

2021-06-28 18:45 UTC, BrettMugglinOlive commented on docs/src/markdown-pages/guides/troubleshooting.md
> +We've already included polyfills in the LDK directly and adding other polyfills should be avoided. If you add other polyfills, the conflicting polyfills may cause problems, and we should check for po
I think that second sentence should be worded "If you add other polyfills, the conflicting polyfills may cause problems, and **you** should check **your** polyfills as part of standard troubleshooting", cause we shouldn't be saying "we" in the context of that sentence

2021-06-28 18:45 UTC, BrettMugglinOlive approved these changes

2021-06-29 12:43 UTC, RusGraf approved these changes

2021-06-29 14:25 UTC, merged